### ISSUE TITLE
Add the Hi-Speed devices cheat sheet

### ISSUE THREAD

**Issue by its-suun** [wiremod/Miscellaneous#1]
http://wiremod.com/forum/showthread.php?t=9315

**Comment by Anticept** [comment]
@its-suun if you can find it in the archives and make a pull request, I'll add it.

**Comment by CaptainPRICE** [comment]
It was [here](http://sebi.com.pl/hscs/), but that was long time ago..

**Comment by gerardsmit** [comment]
There is still a cheat sheet online [here](http://forum.ijwtb.net/showthread.php?tid=7492) and [here](http://www.bybservers.co.uk/index.php?topic=14021.0).

**Comment by Anticept** [comment]
Added by 03825ec4ced3b5c82bd33fc1a988a526ec9f49ae
