### ISSUE TITLE
Trying to put a audio file that I got from Youtube on Sound Emmiters by wiremod and then I clike play there is no sound the on in gmod work but a Mp3 file doesn't please I need some help. 

### ISSUE THREAD

**Issue by ArZe929** [wiremod/Miscellaneous#11]
file:///C:/Users/Coleb/Videos/Captures/Garry's%20Mod%202023-07-02%2017-41-19.mp4
file:///C:/Users/Coleb/Videos/Captures/Garry's%20Mod%202023-07-02%2017-37-54.mp4

**Comment by puyofan99** [comment]
people can't access your files, upload them to somethin' like Google Drive
