### ISSUE TITLE
Bringing the wiki to github

### ISSUE THREAD

**Issue by Anticept** [wiremod/Miscellaneous#3]
As issue title says. This repo will serve as documentation, unless there's a reason to put it in one of the other repos.

**Comment by Divran** [comment]
why use a whole other repo instead of using the wiki tab on the wiremod repo?

**Comment by Anticept** [comment]
Documentation should go with documentation :P

**Comment by Divran** [comment]
meh just don't document that, who cares :v

**Comment by Anticept** [comment]
And adv dupe and adv dupe 2?

**Comment by Nebual** [comment]
Wiremod documentation should go in the Wire repo, Advdupe2 in the Advdupe2 repo, IMO.

There aren't PR's for Wiki's, but its pretty easy to just fork the main repo (which also forks the wiki repo), make your change, then let a contributor know to copy paste the changes over. Or, its possible to merge/cherry-pick wiki commits manually via command line git. 

I'm in the process of converting the E2 wiki page to Github's version of Mediawiki syntax now

**Comment by Anticept** [comment]
So speaketh the devs! :)
