### ISSUE TITLE
2FA login enforcement

### ISSUE THREAD

**Issue by Anticept** [wiremod/Miscellaneous#4]
@wiremod/developers be aware, 2fa enforcement will be turned on soon. I see a few people still without 2fa. I unfortunately can't turn this on per team, it's all or nothing. It's pretty important though to protect against account hacks.

It's also a topic of discussion about what to do with contributors who haven't been around in a long, long while. While 2FA SIGINFICANTLY reduces risk, old accounts with push access are still just unnecessary vectors. Seems the general discussion is going in the direction of retiring members who don't participate at all in wire (even just hanging around and keeping up with people in discord seems to be enough to satisfy participation).

I'm personally thinking about making a CREDITS file in the repo to thank former wiremod devs and provide special thanks to people who made really important contributions.

Thoughts?

**Comment by oldmud0** [comment]
How about sending a big email to all devs without 2FA to turn it on as soon as possible before October 14, and to "check in" their status regarding their affiliation with Wiremod? Then, after that date, everyone who is truly inactive will automatically vanish, and those who have 2FA enabled but are inactive go to some ex-dev team that doesn't have push access.

**Comment by Anticept** [comment]
2FA enforcement is now active.

@oldmud0 it sends out an email about it. I already talked with most of the old devs. Many just said pull their access. Others aren't even responding to my messages so I've removed them for that.

I can always readd when they've got it turned on and reach out to us.
