### ISSUE TITLE
Some real issues with wiremod editor

### ISSUE THREAD

**Issue by ghostserver10** [wiremod/Miscellaneous#9]
![Second](https://user-images.githubusercontent.com/22061441/177060388-e23a9495-9996-4073-8e31-1d2f49e4d4bb.jpg)
Issues with editing. No suggestion
![First](https://user-images.githubusercontent.com/22061441/177060389-648757f3-dfc5-4b92-a99b-2bcf6ffd2c7f.jpg)

Text becomes grey. Strings dont work

**Comment by thegrb93** [comment]
Already reported https://github.com/wiremod/wire/issues/2353
